general:
    logLevel: INFO #[optional]
    attributes_to_read: #equal short names of netcdf-variables
        - TSurf
        # - Albedo
        # - WindSpd
        # - T
        # - LatentHeatFlux
    projectName: kartoza #[optional] Also used for workspacename
    height_levels: [0.3,10.5,40.5]
    inputFile: ./inputFiles/MZ_Flow_2018-07-22_05.00.00-new.nc #[optional]
geoserver:
    url: http://localhost:8600/geoserver
    uploadTimeOut: 20 
frontend:
    path: ./frontend/app #[optional]
    projectHandling: True #If multiple Geoserver Instances are used the projectHandling does not work (If active Deletion of not found workspaces)
styles: #To be defined in Hex Color Code
    DefaultColors: ["#0571b0","#92c5de","#f7f7f7","#f4a582","#ca0020"]
    customStyles:
        Albedo: #[optional]
            colors: ["#000000","#ffffff"]
            values: [0,1] #[optional]
