general:
    logLevel: INFO #[optional]
    attributes_to_read: #equal short names of netcdf-variables
        - TSurf
        - Albedo
        # - WindSpd
        # - T
        # - LatentHeatFlux
    height_levels: [0.3,10.5,40.5] # Could be Integer or Array(to specify specific, existing! HeightLevels)
    removeOutputFiles: False #[optional]
    #workdir: ".." #[DEBUG ONLY]]
    #projectName: mz1 #[DEBUG ONLY]]
    #inputFile: ./inputFiles/MZ_Flow_2018-07-22_05.00.00-new.nc #[DEBUG ONLY]]
geoserver:
    url: http://localhost:8600/geoserver
    user: admin #password will be prompted in main.sh
    uploadTimeOut: 20 #Seconds to Wait until upload is finished
frontend:
    path: ../frontend/app #[optional]
    cleanup: False #[optional] #If active Removal of not found workspaces at Geoserver
styles: #To be defined in Hex Color Code
    nDigits: 2 #[optional] Specify Number of Digits used by rounding in Styles
    DefaultColors: ["#0571b0","#92c5de","#f7f7f7","#f4a582","#ca0020"]
    customStyles:
        Albedo: #[optional]
            colors: ["#000000","#ffffff"]
            values: [0,1] #[optional]
