general:
    EPSG: 900913 #900913 #25832 #900913 # # #3857
    attributes_to_read:
        - TSurf
        - Albedo
        - WindSpd
        - T
    project_name: test #rotated-pole #test 
    height_levels: [0.3,10.5,40.5]
    grid_mapping: "transverse_mercator"  # albers_conical_equal_area
    inputFile:  BVOC_Mainz_IsoOff_2018-07-06_05.00.00.nc #NewSimulation_2018-06-23_05.00.00.nc # #NewSimulation_2018-06-23_05.00.00.nc #BVOC_Mainz_IsoOff_2018-07-06_05.00.00.nc #NewSimulation_2018-06-23_05.00.00.nc #BVOC_Mainz_IsoOff_2018-07-06_05.00.00.nc #NewSimulation_2018-06-23_05.00.00.nc
geoserver:
    url: http://localhost:8080/geoserver
    workspaceName: NetCDF
frontend:
    absolutePath: /Users/eliasborngaesser/src/github.com/eliasborngaesser/netcdf-leaflet/app
styles: #To be defined in Hex Color Code
    DefaultColors: ["#0571b0","#92c5de","#f7f7f7","#f4a582","#ca0020"]
    customStyles:
        Albedo:
            colors: ["#000000","#ffffff"]
            values: [0,1]
